(() => {
    const item = oEvent.oSource.getSelectedItem();
    const data = item.getBindingContext().getObject();

    if (data?.id) {
        const id = NodeID.getText();
        const node = graph.getCellById(id);
        const appType = SelectAppType.getSelectedKey();

        const name = appType === "application" ? data.application : data.name;

        node.attr("title/text",name);
        node.attr("metadata/name",name);
        node.attr("metadata/appType",appType);
        node.attr("metadata/artifactID",data.id);

        modelSelectedNode.getData().name = name;
        Functions.setSize(node);
        modelSelectedNode.refresh();
        visDialog.close();
    }
})();
